services:
  web:
    build: .
    container_name: postal-api
    environment:
      - WEBSERVER_PORT=${WEBSERVER_PORT:9999}
      - DEBUG=${DEBUG:False}
    ports:
      - "${WEBSERVER_PORT:9999}:${WEBSERVER_PORT:9999}"
    volumes:
      - ./data:/var/postal