services:
  web:
    build: .
    container_name: postal-api
    environment:
      - WEBSERVER_PORT=9999
      - DEBUG=False
    ports:
      - 9999:9999
    volumes:
      - ./data:/var/postal